version: "3"

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - "while sleep 1000; do :; done"
    env_file:
      - stt.env
    networks:
      - bridged
networks:
  bridged:
    driver: bridge