FROM registry.access.redhat.com/ubi8/python-39

USER 0
WORKDIR /stt
RUN wget http://www.itzgeek.com/msttcore-fonts-2.0-3.noarch.rpm && rpm -Uvh msttcore-fonts-2.0-3.noarch.rpm \
    && wget https://www.imagemagick.org/download/ImageMagick.tar.gz \
    && mkdir ImageMagick \
    && tar xvzf ImageMagick.tar.gz -C ./ImageMagick --strip-components=1 \
    && pushd ImageMagick && ./configure && make && make install && popd
COPY ./src /stt
COPY ./assets/fonts /usr/local/share/fonts/
RUN python -m venv ~/.venv \
    && echo 'source ~/.venv/bin/activate' >> ~/.bashrc \
    && chmod +x /stt/process.py \
    && pip install -r requirements.txt \
    && mkdir -p /stt/in \
    && mkdir -p /stt/proc \
    && mkdir -p /stt/out \
    && fc-cache /usr/local/share/fonts/