version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile2
    command:
      - /bin/sh
      - -c
      - "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace
      - vscode-server:/home/vscode/.vscode-server

volumes:
  vscode-server: